# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gRnIDCipFYNhuiCOZ7q-cR30KjimxDuq
"""

#smart expence tracker
from datetime import datetime

CATEGORIES=['Food','travel','Bills','Fun','Others']
EXPENCES=[]

def add_new_expence():
    try:
        amount=float(input('enter your amount: Rs '))
        category=input(f"enter the category like {', '.join(CATEGORIES)}. leaving blank will be considered as others: ")
        if category not in CATEGORIES:
            category= 'others'
        date= input('enter date in yyyy-mm-dd format.(leaving blank will be considered as today): ')
        if not date:
            date = datetime.today().strftime("%y-%m-%d")
        note=input('write any note (optional): ')
        EXPENCES.append([category,amount,date,note])
        print('expences added successfully!\n')

    except ValueError:
        print("Invalid input. Please enter numeric values for amount.\n")

def view_all_expences():
  print('all epences:\n')
  for exp in EXPENCES:
    print(f'category = {exp[0]} : amoun t= Rs {exp[1]} : date = {exp[2]} : note = {exp[3]}')
    print()

def view_by_category():
  category=input('enter the category you want to view: ')
  print(f'all epences in {category}:\n')
  total=0
  for exp in EXPENCES:
    if exp[0]==category:
      print(f'category = {exp[0]} : amount= Rs {exp[1]} : date = {exp[2]} : note = {exp[3]}')
      total+=exp[1]
  print(f'your total amount is Rs {total}\n')


def summarize_expences():
  print('summarize of all epences:\n')
  total=0
  for exp in EXPENCES:
    print(f'category = {exp[0]} : amount= Rs {exp[1]} : date = {exp[2]} : note = {exp[3]}')
    total+=exp[1]
  print(f'your total amount is Rs {total}\n')

def main():
    while True:
        print("Smart Expense Tracker")
        print("[1] Add New Expense")
        print("[2] View All Expenses")
        print("[3] View Expenses by Category")
        print("[4] View Monthly Spending Summary")
        print("[5] Exit")
        choice = input("Select an option: ")
        if choice == "1":
            add_new_expence()
        elif choice == "2":
            view_all_expences()
        elif choice == "3":
            view_by_category()
        elif choice == "4":
            summarize_expences()
        elif choice == "5":
            print("Exiting the program.")
            break
        else:
            print("Invalid choice. Please select a valid option.")

if __name__ == "__main__":
    main()

